In [64]:
## ECON 468: ASSIGNMENT 2 BY MAXENCE VAN DIEVOET

In [1]:
# the OLS plot 
### CODE ###
import pandas as pd
from statsmodels.formula.api import ols
import numpy as np
from statsmodels.stats.sandwich_covariance import cov_hac
from math import sqrt

df = pd.read_csv('hw2_data.csv')

print("### RESULTS ###")
fit1 = ols('y ~ x1 + x2 + x3', data=df).fit()
fit1.summary()

In [49]:
# the standard OLS estimate
fit1.cov_params()

Intercept          x1        x2         x3
Intercept  13741.298915 -114.577856  8.044441  67.676030
x1          -114.577856    1.109477 -0.164874  -0.422071
x2             8.044441   -0.164874  0.834828  -0.016892
x3            67.676030   -0.422071 -0.016892   0.574773

In [68]:
### CODE ###
# the four HCCMEs
print("### RESULTS ###")
print("HC0")
fit1.HC0_se
print(fit1.cov_HC0)
print("\nHC1")
fit1.HC1_se
print(fit1.cov_HC1)
print("\nHC2")
fit1.HC2_se
print(fit1.cov_HC2)
print("\nHC3")
fit1.HC3_se
print(fit1.cov_HC3)

### RESULTS ###
HC0
[[ 1.24530797e+04 -9.57197205e+01 -3.72882783e+00  8.31958443e+01]
 [-9.57197205e+01  8.66960180e-01  6.63431413e-02 -4.32988909e-01]
 [-3.72882783e+00  6.63431413e-02  5.68223212e-01  1.48052795e-01]
 [ 8.31958443e+01 -4.32988909e-01  1.48052795e-01  1.03751374e+00]]

HC1
[[ 1.29719580e+04 -9.97080422e+01 -3.88419566e+00  8.66623378e+01]
 [-9.97080422e+01  9.03083521e-01  6.91074389e-02 -4.51030114e-01]
 [-3.88419566e+00  6.91074389e-02  5.91899179e-01  1.54221662e-01]
 [ 8.66623378e+01 -4.51030114e-01  1.54221662e-01  1.08074348e+00]]

HC2
[[ 1.31512097e+04 -1.00699376e+02 -3.45217061e+00  8.87534625e+01]
 [-1.00699376e+02  9.11276205e-01  7.00157549e-02 -4.56216877e-01]
 [-3.45217061e+00  7.00157549e-02  6.06033330e-01  1.68856411e-01]
 [ 8.87534625e+01 -4.56216877e-01  1.68856411e-01  1.11947925e+00]]

HC3
[[ 1.38970463e+04 -1.05998019e+02 -3.11952648e+00  9.47429613e+01]
 [-1.05998019e+02  9.58431782e-01  7.39758838e-02 -4.80899607e-01]
 [-3.11952648e+00  7.397

In [66]:
### CODE ###
# the six versions of the Newey-West HAC estimator
print("### RESULTS ###")
print("truncation parameter = 2")
print(cov_hac(fit1, nlags=2))
print("\ntruncation parameter = 3")
print(cov_hac(fit1, nlags=3))
print("\ntruncation parameter = 4")
print(cov_hac(fit1, nlags=4))
print("\ntruncation parameter = 5")
print(cov_hac(fit1, nlags=5))
print("\ntruncation parameter = 6")
print(cov_hac(fit1, nlags=6))
print("\ntruncation parameter = 20")
print(cov_hac(fit1, nlags=20))

### RESULTS ###
truncation parameter = 2
[[ 1.66155308e+04 -1.27090898e+02 -2.19849570e+01  1.08181107e+02]
 [-1.27090898e+02  1.12705382e+00  2.16322458e-01 -6.14032582e-01]
 [-2.19849570e+01  2.16322458e-01  5.03102095e-01  2.16873164e-02]
 [ 1.08181107e+02 -6.14032582e-01  2.16873164e-02  1.20792381e+00]]

truncation parameter = 3
[[ 1.82549857e+04 -1.40379553e+02 -2.24258045e+01  1.18612937e+02]
 [-1.40379553e+02  1.24241624e+00  2.12836466e-01 -7.02001338e-01]
 [-2.24258045e+01  2.12836466e-01  4.48497779e-01 -1.07063033e-02]
 [ 1.18612937e+02 -7.02001338e-01 -1.07063033e-02  1.25758658e+00]]

truncation parameter = 4
[[ 1.95904413e+04 -1.51793866e+02 -2.51455255e+01  1.26612076e+02]
 [-1.51793866e+02  1.34053854e+00  2.38781028e-01 -7.79948231e-01]
 [-2.51455255e+01  2.38781028e-01  4.24753598e-01 -3.06049066e-02]
 [ 1.26612076e+02 -7.79948231e-01 -3.06049066e-02  1.28779739e+00]]

truncation parameter = 5
[[ 2.02427688e+04 -1.59275506e+02 -2.71667575e+01  1.28096632e+02]
 [-1.59

In [72]:
# using the fact that the covariance of an element with itself is the variance of an element
# Cov(x3,x3)=Var(x3), we get those 11 estimates taking the square root of the (3,3) element of this 4x4 array

### CODE ###
estimate1 = sqrt(0.574773)
# using the four HCCMEs
estimate2 = sqrt(1.03751374)
estimate3 = sqrt(1.08074348)
estimate4 = sqrt(1.11947925)
estimate5 = sqrt(1.20863960)
# using the Newey-West HAC estimator
estimate6 = sqrt(1.20792381)
estimate7 = sqrt(1.25758658)
estimate8 = sqrt(1.28779739)
estimate9 = sqrt(1.25931674)
estimate10 = sqrt(1.22650486)
estimate11 = sqrt(1.46844755)
print("### RESULTS ###")
print("estimate 1:",estimate1)
print("the four HCCMEs")
print("estimate 2:",estimate2)
print("estimate 3:",estimate3)
print("estimate 4:",estimate4)
print("estimate 5:",estimate5)
print("the six Newey_west HACs")
print("estimate 6:",estimate6)
print("estimate 7:",estimate7)
print("estimate 8:",estimate8)
print("estimate 9:",estimate9)
print("estimate 10:",estimate10)
print("estimate 11:",estimate11)

### RESULTS ###
estimate 1: 0.7581378502620747
the four HCCMEs
estimate 2: 1.0185841840515688
estimate 3: 1.039588129982254
estimate 4: 1.0580544645716494
estimate 5: 1.099381462459687
the six Newey_west HACs
estimate 6: 1.0990558721011412
estimate 7: 1.121421678049787
estimate 8: 1.1348116099159367
estimate 9: 1.1221928265676981
estimate 10: 1.1074767988540437
estimate 11: 1.2117951765871986
